Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2021
Var
altura: real
idade: inteiro


Inicio
escreval("Qual sua altura? coloque no lugar da virgula o ponto")
leia(altura)
escreval("Qual sua idade?")
leia(idade)

se ((idade >= 18) e (altura >= 1.75))  entao

escreval("pode competir")

senao

escreval("você não pode competir")

fimse


Fimalgoritmo